# Generated by Django 5.0.6 on 2024-06-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_remove_review_rating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="date",
            field=models.DateField(blank=True),
        ),
    ]
