# Generated by Django 5.0.6 on 2024-06-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_alter_rating_date_alter_review_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
